---
- name: Create security group in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: ap-southeast-2
    security_group_name: ansible-secgrp-ethan-web
    security_group_description: Ethan's Web Server Ansible Security Group
    security_group_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0

  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
        region: "{{ region }}"
        rules: "{{ security_group_rules }}"
