---
- name: Create VPC and Subnet for the Web Servers!
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: ap-southeast-2
    vpc_cidr_block: 172.32.0.0/16
    subnet_cidr_block: 172.32.1.0/24

  tasks:
  - name: Create the VPC
    ec2_vpc_net:
      name: TestVPC
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ region }}"
      state: present

  - name: Create Internet Gateway
    ec2_vpc_igw:
      vpc_id: "{{ vpc.id }}"
      region: "{{ region }}"
      state: present

  - name: Create Public Subnet
    ec2_vpc_subnet:
      vpc_id: "{{ vpc.id }}"
      cidr: "{{ subnet_cidr_block }}"
      region: "{{ region }}"
      state: present
      map_public: true

  - name: Create Route Table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.id }}"
      region: "{{ region }}"
      state: present

  - name: Associate Route Table with Subnet
    ec2_vpc_subnet_route_table:
      subnet_id: "{{ subnet.id }}"
      route_table_id: "{{ route_table.id }}"
      region: "{{ region }}"
      state: present