---
- name: Create VPC, Subnet, and Security Group for the Web Servers!
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: "{{ vpc_region }}"
    vpc_cidr_block: "{{ vpc_cidr_block }}"
    subnet_cidr_block: 

  tasks:
  - name: Create the VPC
    ec2_vpc_net:
      name: TestVPC
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ region }}"
      state: present

  - name: Create Internet Gateway
    ec2_vpc_igw:
      vpc_id: "{{ vpc.id }}"
      region: "{{ region }}"
      state: present

  - name: Create Public Subnet
    ec2_vpc_subnet:
      vpc_id: "{{ vpc.id }}"
      cidr: "{{ subnet_cidr_block }}"
      region: "{{ region }}"
      state: present
      map_public: true

  - name: Create Route Table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc.id }}"
      region: "{{ region }}"
      state: present

  - name: Associate Route Table with Subnet
    ec2_vpc_subnet_route_table:
      subnet_id: "{{ subnet.id }}"
      route_table_id: "{{ route_table.id }}"
      region: "{{ region }}"
      state: present

  - name: Create security group
    ec2_group:
      name: "{{ security_group_name }}"
      description: "{{ security_group_description }}"
      region: "{{ region }}"
      rules: "{{ security_group_rules }}"
