---

- name: Create security group in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_description }}"
        region: "{{ region }}"
        rules: "{{ security_group_rules }}"
