---
- name: Launch EC2 instances, and install Web Services
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Launch EC2 instance for Web Server 1
    test-httpd1:
      key_name: "{{ key_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image_id1 }}"
      group: "{{ security_group }}"
      subnet_id: "{{ subnet_id }}"
      region: "{{ region }}"
      count: "{{ count }}"
      wait: true
      assign_public_ip: true
    register: ec2_instance

  - name: Launch EC2 instance for Web Server 2
    test-httpd2:
      key_name: "{{ key_name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image_id2 }}"
      group: "{{ security_group }}"
      subnet_id: "{{ subnet_id }}"
      region: "{{ region }}"
      count: "{{ count }}"
      wait: true
      assign_public_ip: true
    register: ec2_instance

  - name: Print instance information
    debug:
      var: ec2_instance.instances[0].public_ip

- name: Configure httpd on EC2 instance 1
  hosts: test-httpd1
  become: true
  gather_facts: false

  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: latest

  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: true

- name: Configure httpd on EC2 instance 2
  hosts: test-httpd2
  become: true
  gather_facts: false

  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: latest

  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: true
